// <auto-generated />
using System;
using CarlosAOliveira.Developer.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarlosAOliveira.Developer.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20250910130445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarlosAOliveira.Developer.Domain.Entities.DailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MerchantId");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NetAmount");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalCredits");

                    b.Property<decimal>("TotalDebits")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalDebits");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int")
                        .HasColumnName("TransactionCount");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DailySummaries_Date");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("IX_DailySummaries_MerchantId");

                    b.HasIndex("MerchantId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailySummaries_MerchantId_Date");

                    b.ToTable("DailySummaries", (string)null);
                });

            modelBuilder.Entity("CarlosAOliveira.Developer.Domain.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Merchants_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Merchants_Email");

                    b.ToTable("Merchants", (string)null);
                });

            modelBuilder.Entity("CarlosAOliveira.Developer.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MerchantId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Transactions_CreatedAt");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("IX_Transactions_MerchantId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Transactions_Type");

                    b.HasIndex("MerchantId", "CreatedAt")
                        .HasDatabaseName("IX_Transactions_MerchantId_CreatedAt");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("CarlosAOliveira.Developer.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CarlosAOliveira.Developer.Domain.Entities.DailySummary", b =>
                {
                    b.HasOne("CarlosAOliveira.Developer.Domain.Entities.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarlosAOliveira.Developer.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CarlosAOliveira.Developer.Domain.Entities.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
